// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.6.1
// source: rpc/infofile.proto

package rpc

import (
	_struct "github.com/golang/protobuf/ptypes/struct"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoFileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Hash    string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *InfoFileRequest) Reset() {
	*x = InfoFileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_infofile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoFileRequest) ProtoMessage() {}

func (x *InfoFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_infofile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoFileRequest.ProtoReflect.Descriptor instead.
func (*InfoFileRequest) Descriptor() ([]byte, []int) {
	return file_rpc_infofile_proto_rawDescGZIP(), []int{0}
}

func (x *InfoFileRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InfoFileRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoFileRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type InfoFileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string          `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Version string          `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Hash    string          `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Content *_struct.Struct `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *InfoFileResponse) Reset() {
	*x = InfoFileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_infofile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoFileResponse) ProtoMessage() {}

func (x *InfoFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_infofile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoFileResponse.ProtoReflect.Descriptor instead.
func (*InfoFileResponse) Descriptor() ([]byte, []int) {
	return file_rpc_infofile_proto_rawDescGZIP(), []int{1}
}

func (x *InfoFileResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InfoFileResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoFileResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *InfoFileResponse) GetContent() *_struct.Struct {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_rpc_infofile_proto protoreflect.FileDescriptor

var file_rpc_infofile_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x70, 0x63, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x53, 0x0a, 0x0f, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x87, 0x01, 0x0a, 0x10, 0x49, 0x6e, 0x66, 0x6f,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x31,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x32, 0x44, 0x0a, 0x0f, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x08, 0x4c, 0x6f, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x65,
	0x12, 0x10, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x11, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x72, 0x70, 0x63, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_infofile_proto_rawDescOnce sync.Once
	file_rpc_infofile_proto_rawDescData = file_rpc_infofile_proto_rawDesc
)

func file_rpc_infofile_proto_rawDescGZIP() []byte {
	file_rpc_infofile_proto_rawDescOnce.Do(func() {
		file_rpc_infofile_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_infofile_proto_rawDescData)
	})
	return file_rpc_infofile_proto_rawDescData
}

var file_rpc_infofile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_infofile_proto_goTypes = []interface{}{
	(*InfoFileRequest)(nil),  // 0: InfoFileRequest
	(*InfoFileResponse)(nil), // 1: InfoFileResponse
	(*_struct.Struct)(nil),   // 2: google.protobuf.Struct
}
var file_rpc_infofile_proto_depIdxs = []int32{
	2, // 0: InfoFileResponse.content:type_name -> google.protobuf.Struct
	0, // 1: InfoFileService.LoadFile:input_type -> InfoFileRequest
	1, // 2: InfoFileService.LoadFile:output_type -> InfoFileResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_infofile_proto_init() }
func file_rpc_infofile_proto_init() {
	if File_rpc_infofile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_infofile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoFileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_infofile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoFileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_infofile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_infofile_proto_goTypes,
		DependencyIndexes: file_rpc_infofile_proto_depIdxs,
		MessageInfos:      file_rpc_infofile_proto_msgTypes,
	}.Build()
	File_rpc_infofile_proto = out.File
	file_rpc_infofile_proto_rawDesc = nil
	file_rpc_infofile_proto_goTypes = nil
	file_rpc_infofile_proto_depIdxs = nil
}
