# MongoDB configuration
mongodb:
  database:
    name: store
    connection:
      host: localhost
      port: 27017
      username: mongodb
      password: DB_PASSWORD

file-storage:
  storage-dir: ./resources
  file-pattern: "{{type}}-{{version}}.json"

rpc:
  server:
    host: 0.0.0.0
    port: 50051