# MongoDB configuration
mongodb:
  database:
    name: dbTest
    connection:
      host: localhost
      port: 37017
      username: mongodb
      password: TEST_DB_PASSWORD

file-storage:
  storage-dir: directory
  file-pattern: "{{type}}-{{version}}.json"

rpc:
  server:
    host: 0.0.0.0
    port: 50051